const resumeData = {
  name: "Karthika Nair P",
  title: "Software Developer",
  subtitle: "Full-Stack & AI Solutions Engineer",
  location: "Kottayam, Kerala",
  contact: {
    phone: "+91 9526661665",
    email: "karthikanairprasannakumar84@gmail.com",
    linkedin:
      "https://www.linkedin.com/in/karthika-nair-prasannakumar-65085a214/",
    github: "https://github.com/karthikanairp4?tab=repositories",
    portfolio: "https://karthikanair.dev",
  },
  summary:
    "Software Developer with 3+ years of experience designing and developing enterprise applications using Java, Spring Boot, Vue.js, REST APIs, SQL, and MySQL. Experienced in building scalable backend systems, secure authentication using OAuth 2.0 and ForgeRock, production support, and Agile software development. Hands-on experience developing AI-powered applications using LLMs, RAG, and vector databases.",
  skills: {
    languages: ["Java", "JavaScript", "SQL", "PHP", "HTML5", "CSS3"],
    backend: [
      "Spring Framework",
      "Spring Boot",
      "Spring MVC",
      "Spring Data JPA",
      "Hibernate",
      "Node.js",
      "Laravel",
    ],
    frontend: [
      "Vue.js (Vue 3)",
      "Bootstrap",
      "Pinia",
      "Vue Router",
      "Vanilla JS",
    ],
    databases: [
      "MySQL",
      "SQL Server",
      "MongoDB",
      "Firebase",
      "Snowflake",
      "DynamoDB",
    ],
    ai_ml: [
      "LLMs",
      "Retrieval-Augmented Generation (RAG)",
      "FAISS",
      "Ollama",
      "Hugging Face",
      "Prompt Engineering",
    ],
    security: [
      "REST APIs",
      "OAuth 2.0",
      "JWT",
      "ForgeRock Identity Management",
      "BCrypt",
      "RBAC",
    ],
    tools: [
      "Git",
      "GitHub",
      "Azure DevOps",
      "Azure App Insights",
      "Maven",
      "Postman",
      "Power BI",
      "Streamlit",
      "n8n",
    ],
  },
  experience: [
    {
      role: "Software Developer",
      company: "Antec Controls, Price Industries",
      location: "Winnipeg, Manitoba, Canada",
      period: "Aug 2025 – Jun 2026",
      tech: [
        "Vue.js",
        "PHP",
        "MySQL",
        "C#",
        "Power BI",
        "Azure",
        "ForgeRock",
        "OAuth",
        "Git",
        "Azure DevOps",
      ],
      highlights: [
        "Developed and enhanced enterprise applications, including the Quick Pricing Tool and Antec Select Web Tool, implementing bug fixes and feature enhancements to improve application functionality and reliability.",
        "Integrated Azure Application Insights with Power BI dashboards to centralize application telemetry, monitor application behavior, and support reporting and production troubleshooting.",
        "Implemented and supported ForgeRock Identity Management and OAuth 2.0-based authentication workflows, including automation scripts for user provisioning and access management.",
        "Diagnosed and resolved production issues through debugging, log analysis, telemetry, and database investigation, performing root-cause analysis and implementing corrective fixes.",
        "Developed enhancements for the Antec Excel Toolkit using C# and contributed to website modernization using WordPress while maintaining technical documentation.",
      ],
    },
    {
      role: "Systems Engineer",
      company: "Infosys Limited",
      location: "Trivandrum, Kerala, India",
      period: "Jan 2022 – Apr 2024",
      tech: [
        "Java",
        "Spring Boot",
        "Spring Framework",
        "Hibernate",
        "JPA",
        "REST APIs",
        "SQL Server",
        "MongoDB",
        "Snowflake",
        "Hive",
        "DynamoDB",
        "Git",
      ],
      highlights: [
        "Developed enterprise applications using desktop, monolithic, and microservices architectures with Java, Spring Boot, Spring Framework, REST APIs, and multiple relational and NoSQL databases.",
        "Developed enterprise modules for the Infosys Enterprise Data Privacy Suite (IEDPS) using Java, Spring Boot, Spring Framework, and REST APIs across 5 core modules.",
        "Built features across Data Masking, Data Discovery, Inventory Management, Data Generation, and User Management while integrating MySQL, SQL Server, MongoDB, Snowflake, and DynamoDB.",
        "Implemented enterprise data masking solutions for Transamerica client and integrated third-party services to improve system interoperability.",
        "Provided production support through debugging, root cause analysis, code reviews, Agile development, and technical documentation.",
      ],
    },
  ],
  education: [
    {
      degree: "Post-Graduate Program in Web Application Development",
      institution: "University of Winnipeg - PACE",
      location: "Winnipeg, MB, Canada",
      period: "May 2024 – May 2025",
      score: "CGPA: 4.0 / 4.5",
    },
    {
      degree: "Bachelor of Technology (B.Tech Hons.) in Civil Engineering",
      institution: "College of Engineering, Kidangoor (KTU)",
      location: "Kottayam, Kerala, India",
      period: "Aug 2017 – Aug 2021",
      score: "CGPA: 8.33 / 10",
    },
  ],
  certifications: [
    "Infosys Certified Java Developer",
    "Infosys Certified Microservice Developer",
    "Infosys Certified Frontend Web Developer",
    "Infosys Certified Spring REST Professional",
    "Infosys Certified Global Agile Developer",
    "Generative AI Fundamentals - Databricks",
  ],
  projects: [
    {
      id: "ecommerce",
      title: "Full-Stack eCommerce & AI Insights Application",
      category: "fullstack",
      subtitle: "Java, Spring Boot, Vue 3, MySQL, Gemini AI, n8n",
      description:
        "A full-stack bakery eCommerce platform featuring responsive Vue 3 frontend, Spring Boot REST API backend, Gemini AI sales insights, and automated daily sales report generation.",
      details: [
        "Implemented Spring Security, OAuth 2.0, JWT, BCrypt, and RBAC for secure customer and admin authentication.",
        "Developed product catalog, live search, cart, order management, user profiles, admin panel, and custom cake builder with dynamic pricing.",
        "Integrated Google Gemini AI to analyze sales trends and generate actionable business recommendations.",
        "Built automated daily sales PDF reporting system integrated with n8n + Gmail SMTP for scheduled distribution.",
      ],
      tech: [
        "Java",
        "Spring Boot",
        "Vue 3",
        "Pinia",
        "MySQL",
        "Gemini AI",
        "n8n",
        "Bootstrap",
        "REST APIs",
      ],
      github: "https://github.com/karthikanairp4?tab=repositories",
      live: "https://paprika-bakes.netlify.app/",
    },
    {
      id: "pulse",
      title: "Pulse - A user friendly Blogging Platform",
      category: "fullstack",
      subtitle: "Node.js, Express.js, REST APIs, JavaScript, HTML5/CSS3",
      description:
        "A responsive web dashboard application designed for health metric tracking, real-time data visualization, and user analytics.",
      details: [
        "Designed and built interactive web interface using Vue.js, reusable components, and responsive layouts.",
        "Integrated REST APIs for real-time data synchronization, user tracking, and metrics visualization.",
        "Implemented clean state management and modern CSS styling for an engaging user experience.",
      ],
      tech: [
        "Node.js",
        "Express.js",
        "JavaScript",
        "REST APIs",
        "HTML5",
        "CSS3",
        "Git",
        "Bootstrap",
      ],
      github: "https://github.com/karthikanairp4/pulse_by-karthika",
      live: "https://pulse-by-karthika.vercel.app/",
    },
    {
      id: "cargo",
      title: "CarGo - Vehicle Reservation Platform",
      category: "fullstack",
      subtitle: "Node.js, Express.js, MySQL, Bootstrap",
      description:
        "A web-based vehicle reservation platform featuring an integrated booking engine, user role management, and payment processing logic.",
      details: [
        "Built with Laravel, MySQL, and Bootstrap for a structured MVC web application.",
        "Integrated an interactive booking engine, multi-tier user role management (customers & administrators), and payment logic.",
        "Designed and implemented relational database schemas for vehicle inventory, active reservations, and user accounts.",
      ],
      tech: [
        "Node.js",
        "Express.js",
        "MySQL",
        "Bootstrap",
        "JavaScript",
        "HTML5/CSS3",
        "Stripe API",
      ],
      github: "https://github.com/karthikanairp4/CarGo",
      live: "https://cargo-b2va.onrender.com/",
    },
    {
      id: "rag-assistant",
      title: "AI-Powered Knowledge Assistant (RAG)",
      category: "ai",
      subtitle: "Python, Streamlit, Ollama, FAISS, Hugging Face",
      description:
        "An AI-powered knowledge assistant for semantic document search and conversational QA using Retrieval-Augmented Generation (RAG) with local LLMs.",
      details: [
        "Implemented document ingestion pipeline with smart text chunking, vector indexing with FAISS, and Hugging Face embeddings.",
        "Leveraged local LLM inference via Ollama for privacy-focused, zero-leakage enterprise document search.",
        "Designed an intuitive Streamlit interface allowing users to upload PDFs/Docs and receive context-aware, cited answers.",
      ],
      tech: [
        "Python",
        "Streamlit",
        "Ollama",
        "FAISS",
        "Hugging Face",
        "RAG",
        "LLMs",
        "Prompt Engineering",
      ],
      github: "https://github.com/karthikanairp4?tab=repositories",
      live: "#",
    },
    {
      id: "wpg-wallet",
      title: "WPG Wallet - Personal Finance Application",
      category: "fullstack",
      subtitle: "Node.js, Express.js, Firebase, MySQL",
      description:
        "A full-stack personal finance and budget analytics app featuring real-time transaction workflows, security authentication, and financial reporting.",
      details: [
        "Implemented secure user authentication with Firebase Auth & OAuth 2.0 integration.",
        "Engineered RESTful services for fund transfers, account tracking, budget targets, and financial analytics.",
        "Designed modular architecture with real-time push notification workflows for transaction alerts.",
      ],
      tech: [
        "Node.js",
        "Express.js",
        "Firebase",
        "MySQL",
        "REST APIs",
        "JavaScript",
        "HTML/CSS",
        "Plaid API",
      ],
      github: "https://github.com/karthikanairp4/wpg-wallet-knp",
      live: "#",
    },
  ],
};
